# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - prjg5-attendance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://prjattendanceregistry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2b456144606c42959a7fd25cf232fe4d }}
        password: ${{ secrets.AzureAppService_ContainerPassword_859715885bf745f2b034f7a7a5da5e27 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: prjattendanceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2b456144606c42959a7fd25cf232fe4d }}/app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'prjg5-attendance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_efbc3b97761b41319e6ca9ff9bb72bc8 }}
        images: 'prjattendanceregistry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2b456144606c42959a7fd25cf232fe4d }}/app:${{ github.sha }}'